%{ if tracing_enabled }
traces:
  enabled: true
  podAnnotations:
    instrumentation.opentelemetry.io/inject-sdk: "opentelemetry/default-instrumentation"
%{ else }
traces:
  enabled: false
%{ endif }