image:
  repository: ${image_repository}
  tag: ${image_tag}

redis:
  create: false

  address: ${redis_address}
  port: ${redis_port}

endpoints:
  orders: http://orders.orders.svc:80

%{ if opentelemetry_enabled }
opentelemetry:
  enabled: true
  instrumentation: ${opentelemetry_instrumentation}
%{ else }
securityGroups:
  create: true

  securityGroupIds:
  - ${security_group_id}
%{ endif }