redis:
  create: false

  address: ${redis_address}
  port: ${redis_port}

endpoints:
  orders: http://orders.orders.svc:80

%{ if tracing_enabled }
securityGroups:
  create: false

traces:
  enabled: true
  podAnnotations:
    instrumentation.opentelemetry.io/inject-sdk: "opentelemetry/default-instrumentation"
%{ else }
securityGroups:
  create: true

  securityGroupIds:
  - ${security_group_id}
traces:
  enabled: false
%{ endif }