mysql:
  create: false

  endpoint: ${database_endpoint}

  secret:
    username: ${database_username}
    password: "${database_password}"

rabbitmq:
  create: false
  
  address: ${rabbitmq_endpoint}

  secret:
    username: ${rabbitmq_username}
    password: "${rabbitmq_password}"

%{ if opentelemetry_enabled }
opentelemetry:
  enabled: true
  instrumentation: "opentelemetry/default-instrumentation"
%{ else }
securityGroups:
  create: true

  securityGroupIds:
  - ${security_group_id}
%{ endif }