image:
  repository: ${image_repository}
  tag: ${image_tag}

postgresql:
  create: false

  database: ${database_name}

  endpoint:
    host: ${database_endpoint_host}
    port: "${database_endpoint_port}"

  secret:
    username: ${database_username}
    password: "${database_password}"

rabbitmq:
  create: false
  
  address: ${rabbitmq_endpoint}

  secret:
    username: ${rabbitmq_username}
    password: "${rabbitmq_password}"

%{ if opentelemetry_enabled }
opentelemetry:
  enabled: true
  instrumentation: ${opentelemetry_instrumentation}
%{ else }
securityGroups:
  create: true

  securityGroupIds:
  - ${security_group_id}
%{ endif }