endpoints:
  catalog: http://catalog.catalog.svc:80
  carts: http://carts.carts.svc:80
  orders: http://orders.orders.svc:80
  assets: http://assets.assets.svc:80
  checkout: http://checkout.checkout.svc:80

%{ if opentelemetry_enabled }
opentelemetry:
  enabled: true
  instrumentation: "opentelemetry/default-instrumentation"
%{ endif }

%{ if istio_enabled }
istio:
  enabled: true
  hosts:
  - "*"
%{ else }
service:
  type: LoadBalancer
%{ endif }