endpoints:
  catalog: http://catalog.catalog.svc:80
  carts: http://carts.carts.svc:80
  orders: http://orders.orders.svc:80
  assets: http://assets.assets.svc:80
  checkout: http://checkout.checkout.svc:80

%{ if tracing_enabled }
traces:
  enabled: true
  podAnnotations:
    instrumentation.opentelemetry.io/inject-sdk: "opentelemetry/default-instrumentation"
%{ else }
traces:
  enabled: false
%{ endif }

%{ if istio_enabled }
istio:
  enabled: true
  hosts:
  - "*"
%{ else }
service:
  type: LoadBalancer
%{ endif }