name: E2E Test

on:
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
    - 'images/**'
    - 'deploy/docker-compose/**'
  workflow_dispatch:

jobs:
  build:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: e2e-buildx
      uses: docker/setup-buildx-action@v2

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2

    - name: Set up QEMU
      id: e2e-qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Build Images
      run: |
        (cd deploy/docker-compose && COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build -q)
        
    - name: Run Tests
      run: |
        (cd deploy/docker-compose && MYSQL_PASSWORD='test123' docker-compose up -d)
        (cd src/e2e && bash ./scripts/run-docker.sh -n docker-compose_default 'http://ui:8080')
        (cd deploy/docker-compose && docker-compose down)
