name: Publish Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
    
permissions:
  id-token: write
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ["ui", "catalog", "cart", "checkout", "orders", "assets", "load-generator"]
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Get AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GithubActionsSession
      
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2

    - name: Build Images
      env:
        TAG: "${{ github.event.inputs.tag }}"
        SERVICE: "${{ matrix.service }}"
      run: |
        scripts/build-image.sh -r 'public.ecr.aws/aws-containers' -t $TAG -p --multi-arch --actions-cache -s $SERVICE

    
